name: CI Pipeline

on:
  push:
    branches:
      - main
      - development
      - testing-ci
  pull_request:
    branches:
      - main
      - development
      - testing-ci

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install CLI dependencies
        run: |
          npm ci
        working-directory: client

      - name: Build client
        run: |
          npm run build-only
        working-directory: client

      - name: Setup server
        run: |
          pip install -r requirements.txt 
          flask db init 
          flask db migrate 
          flask db upgrade
        working-directory: /

      - name: Build server
        run: |
          npm run start-flask
        working-directory: client

      - name: Verify server is running
        run: |
          curl localhost:8000